server:
  port: 8081

spring:
  application:
    name: UserService
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:userdb
    username: sa
    password: password
    driverClassName: org.h2.Driver

